### ISSUE TITLE
Improve the readme file and add more info

### ISSUE THREAD

**Issue by zippytyro** [zippytyro/Simon-game#1]
_Visit the website - [here](https://simon-game.ml/)
Improve the readme file to add more details about the website.
Add a screenshot if necessary._
--------------------------------------
### How to contribute
- Fork this repo
- clone it to your own machine 
- create a new branch naming it as your username
- Edit the required files
- Commit and push

After that make PR
Thanks

**Comment by paulopacitti** [comment]
I love to write beautiful `README.md` files ✨ , I can work on this! Could you assign me?

**Comment by zippytyro** [comment]
@paulopacitti all yours

**Comment by Rohan-GD** [comment]
is the issue still open, maybe i can try it too if possible.
